### ISSUE TITLE
Help about tokenizer

### ISSUE THREAD

**Issue by Liangliangb** [resloved/RWKV-notebooks#4]
Hello, I am a novice, I have an error when running file RWKV_v2_RNN_Pile_Fine_Tuning.ipynb, 
Position 8 tokenizer = PreTrainedTokenizerFast(tokenizer_file=f'{repo_dir}/20B_tokenizer.json') in Training Data Options, 
It prompts me with an Exception: No such file or directory (os error 2). So I want to know how I can get this file.

**Comment by resloved** [comment]
Looks like the file structure changed since I last used that notebook. I've updated it so it works properly now (https://github.com/resloved/RWKV-notebooks/commit/7163a8f3a244df500f239418ae6c0d72569adc2b)

As a side note, the v2 and v3 notebooks are for legacy purposes. If you don't have a specific reason to use them I'd recommend using the v4neo one as it is much more stable (and RWKV-v4 models preform much better).

**Comment by Liangliangb** [comment]
Okay, thank you for your suggestion
